### ISSUE TITLE
A lot of libraries in requirements.txt

### ISSUE THREAD

**Issue by ukBaz** [nullp0tr/bluew#1]
There are a lot of libraries in requirements.txt that don't seem to be used.

Are they all required for an end user to experiment with your library?

**Comment by nullp0tr** [comment]
The requirements.txt is outdated, I'll fix it later:) I think some of them got pulled because of nosetests and the testconfig plugin for it. But you definitely don't need them all!

**Comment by nullp0tr** [comment]
The only required library for it to run is actually dbus-python, I added vext.gi cause it helps import gi.repository from a virtualenv. I also removed the libraries needed for nosetests.

**Comment by ukBaz** [comment]
Thanks
