### ISSUE TITLE
Can i use it with kivy to make an app?

### ISSUE THREAD

**Issue by BooHan** [nullp0tr/bluew#18]
Can i use it with kivy to make an app?

**Comment by nullp0tr** [comment]
do you mean just for android? this has a direct dependency on linux because of bluez

**Comment by BooHan** [comment]
yes for android..sorry i'm noobz what do you mean with that? can I or no?

**Comment by nullp0tr** [comment]
I think for normal apps it probably won't work. I don't think most androids come with the required dependencies. Maybe just try it out and let me know what errors you run into?

**Comment by BooHan** [comment]
Not working with kivy...sorry for the questio but have any idea of what library can i use for bluetooth and kivy?

**Comment by nullp0tr** [comment]
sorry nope:(. if kiwi has a way to interface directly with the android sdk you might wanna try that.
