### ISSUE TITLE
Connected attribute is not reflecting the real connection state

### ISSUE THREAD

**Issue by bjoernh** [nullp0tr/bluew#9]
I'm playing a little bit with bluew and i like the API design a lot, but i run into a curious state.
Steps to reproduce:
1. have a bluetooth device already paired and connected

    \>>> import bluew
    \>>> connected_devices = [ dev for dev in bluew.devices() if dev.connected == True ]
    \>>> print(connected_device)
    [<bluew.device.Device object at 0x7f53826580b8>]
    \>>> print(connected_device[0].connected)
    True

2. Looks fine. Now disconnect the device by e.g. bluetoothctl or powering off (not by bluew)

    \>>> print(connected_device[0].connected)
    True

I assume False but True is still returned. It looks like bluew is not asking bluez over dbus for the connection state when the attribute is read. Maybe it only greps the state from bluez only when bluew creates the object?

**Comment by nullp0tr** [comment]
I'm glad you like it:) and yes you're right, state is only queried when devices() is called and currently the only way is to call info(mac) to query it again. I'll add real-time querying to device objects later today, so that dev.attr always reflects the current state.

**Comment by nullp0tr** [comment]
@bjoernh can you test out the latest commit https://github.com/nullp0tr/bluew/commit/2bbb55abbc0e8a45031a89e3e43fd97c0de2007f on the dev branch?:) It should now query the state on every attribute access!

**Comment by nullp0tr** [comment]
This is fixed by https://github.com/nullp0tr/bluew/commit/365039ccfd2cc36007b2e09bc76691405a83f118
